name: r-reticulate
channels:
  - conda-forge
dependencies:
  - python[version='>=3.9']
  - ipykernel
  - ipywidgets
  - earthengine-api
  - google-cloud-sdk
  - rioxarray
  - eemont
  - geopandas
  - numba
  - owslib
  - wxee
  - pip
  - jupyter
  - notebook
  - ca-certificates
  - certifi
  - openssl
  - pip:
    - alive-progress
    - geedim
    - termcolor