install.packages("reticulate")
install.packages("remotes")
remotes::install_github("sydney-informatics-hub/dataharvester")
reticulate::install_miniconda(update = FALSE, force = TRUE)
dataharvester::initialise_harvester(envname = "r-reticulate")
