install.packages("remotes")
install.packages("startup")
remotes::install_github("sydney-informatics-hub/dataharvester", ref = "develop")
reticulate::install_miniconda()
startup::restart() 
reticulate::conda_remove("r-reticulate")
reticulate::conda_create(envname = "r-reticulate", environment = "environment.yml")